# Generated by Django 5.1.15 on 2026-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_book', 'Nouveau livre ajouté'), ('book_available', 'Livre disponible'), ('request_approved', 'Demande approuvée'), ('request_rejected', 'Demande rejetée'), ('new_request', "Nouvelle demande d'emprunt"), ('extension_approved', 'Prolongation approuvée'), ('extension_rejected', 'Prolongation rejetée'), ('loan_due', "Rappel d'échéance"), ('loan_overdue', 'Prêt en retard')], max_length=50),
        ),
    ]
