# Generated by Django 5.1.15 on 2026-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=200)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('edition', models.CharField(blank=True, max_length=100, null=True)),
                ('publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('year_published', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
                ('number_of_copies', models.PositiveIntegerField(default=1)),
                ('availability', models.CharField(choices=[('available', 'Disponible'), ('borrowed', 'Emprunté'), ('reserved', 'Réservé')], default='available', max_length=20)),
            ],
            options={
                'db_table': 'books',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title'], name='books_title_7a737c_idx'), models.Index(fields=['author'], name='books_author_1c43f5_idx'), models.Index(fields=['availability'], name='books_availab_b2d03d_idx')],
            },
        ),
    ]
