# Generated by Django 5.1.15 on 2026-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_avatar_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Employé'), ('book_manager', 'Gestionnaire livres'), ('request_manager', 'Gestionnaire demandes'), ('admin', 'Administrateur')], default='employee', max_length=20),
        ),
    ]
